### ISSUE TITLE
KeyError: 'autotags'

### ISSUE THREAD

**Issue by yqrashawn** [novoid/lazyblorg#12]
revision f8bf1b6
python version 2.7.13
os macOS 10.12.5  

reproducing:
```shell
git clone https://github.com/novoid/lazyblorg.git
cd lazyblorg
sh example_invocation.sh
```
err:
```log
Warning: DIRECTORIES_WITH_IMAGE_ORIGINALS[1] which is set to "/Users/yqrashawn/tmp/digicam/tmp" is not an existing directory. It will be ignored.
Warning: DIRECTORIES_WITH_IMAGE_ORIGINALS[2] which is set to "/Users/yqrashawn/archive/events_memories/2017" is not an existing directory. It will be ignored.
Warning: DIRECTORIES_WITH_IMAGE_ORIGINALS[3] which is set to "/Users/yqrashawn/archive/fromweb/cliparts" is not an existing directory. It will be ignored.
Warning: MEMACS_FILE_WITH_IMAGE_FILE_INDEX is not empty but contains no existing file. Please fill it with an existing filename containing a Memacs file index or set either MEMACS_FILE_WITH_IMAGE_FILE_INDEX or CUSTOMIZED_IMAGE_LINK_KEY to an empty string.
Warning: IMAGE_CACHE_DIRECTORY is set but points to a directory which does not exist. Either empty the string or create its cache directory at "/Users/yqrashawn/src/lazyblorg/testdata/imagecache".
WARNING  Blog data file "./NONEXISTING_-_REPLACE_WITH_YOUR_PREVIOUS_METADATA_FILE.pk" is not found. Assuming first run!
INFO     Parsing "testdata/end_to_end_test/orgfiles/test.org" ...
INFO     Parsing "testdata/end_to_end_test/orgfiles/about-placeholder.org" ...
INFO     Parsing "templates/blog-format.org" ...
INFO     no previous metadata found: must be the first run of lazyblorg with this configuration
Traceback (most recent call last):
  File "./lazyblorg.py", line 581, in <module>
    generate, marked_for_feed, increment_version)
  File "./lazyblorg.py", line 182, in generate_output
    return htmlizer.run()  # FIXXME: return value?
  File "/Users/yqrashawn/projects/lazyblorg/lib/htmlizer.py", line 186, in run
    stats_generated_persistent, stats_generated_tags = self._generate_pages_for_tags_persistent_temporal()
  File "/Users/yqrashawn/projects/lazyblorg/lib/htmlizer.py", line 342, in _generate_pages_for_tags_persistent_temporal
    entry)
  File "/Users/yqrashawn/projects/lazyblorg/lib/htmlizer.py", line 1844, in _generate_persistent_article
    content += self._generate_back_references_content(entry, config.PERSISTENT)
  File "/Users/yqrashawn/projects/lazyblorg/lib/htmlizer.py", line 1674, in _generate_back_references_content
    if 'language' in entry['autotags'].keys() and entry['autotags']['language'] == 'deutsch':
KeyError: 'autotags'
```

**Comment by novoid** [comment]
Thanks for the report. I'll look into it. Unfortunately, I'm off-keyboard for a week from now on.

**Comment by yqrashawn** [comment]
I add similar codes, it works.

**Comment by novoid** [comment]
I'm going to re-open the issue until I solved it in the repository.

**Comment by novoid** [comment]
Fixed.
