### ISSUE TITLE
Config Parameters could not be empty

### ISSUE THREAD

**Issue by diovon** [novoid/lazyblorg#39]
Now I have the problem with the new config parameter ID_OF_HOWTO_PAGE. I don't have such a page and therefore I will set it to ' ' or comment it out. But when generating the blog I got error, because this parameter is mandatory.

**Comment by diovon** [comment]
My current workaround is to set the about page and comment out the ID_OF_HOWTO_PAGE in the blog-template file.

By the way empty sting is not allowed by the system and I get errors at blog generation>

Tried ID_OF_HOWTO_PAGE=''

Error-Message: Traceback (most recent call last):
  File "./lazyblorg.py", line 14, in <module>
    import config  # lazyblorg-global settings from "config.py"
  File "/home/andreas/git/lazyblorg/config.py", line 140, in <module>
    assert(len(ID_OF_HOWTO_PAGE) > 0)
AssertionError

Tried ID_OF_HOWTO_PAGE=' '

Error-Message: ERROR    blog_data_with_id(" ") did not find exactly one result (as expected): [[]]. Maybe you mistyped an internal link id (or there are multiple blog entries sharing IDs)?
Traceback (most recent call last):
  File "./lazyblorg.py", line 587, in <module>
    statistics_list = lazyblorg.generate_output(generate, marked_for_feed, increment_version)
  File "./lazyblorg.py", line 181, in generate_output
    return htmlizer.run()  # FIXXME: return value?
  File "/home/andreas/git/lazyblorg/lib/htmlizer.py", line 205, in run
    stats_generated_persistent, stats_generated_tags = self._generate_pages_for_tags_persistent_temporal(tags)
  File "/home/andreas/git/lazyblorg/lib/htmlizer.py", line 367, in _generate_pages_for_tags_persistent_temporal
    entry)
  File "/home/andreas/git/lazyblorg/lib/htmlizer.py", line 1954, in _generate_temporal_article
    htmlcontent = self.sanitize_internal_links(htmlcontent)
  File "/home/andreas/git/lazyblorg/lib/htmlizer.py", line 1701, in sanitize_internal_links
    url = self.generate_absolute_url(targetid)
  File "/home/andreas/git/lazyblorg/lib/htmlizer.py", line 1657, in generate_absolute_url
    url_for_the_target_id = self._target_path_for_id_without_targetdir(targetid)
  File "/home/andreas/git/lazyblorg/lib/htmlizer.py", line 2270, in _target_path_for_id_without_targetdir
    entry = self.blog_data_with_id(entryid)
  File "/home/andreas/git/lazyblorg/lib/htmlizer.py", line 2375, in blog_data_with_id
    raise HtmlizerException(self.current_entry_id, message)
lib.htmlizer.HtmlizerException: 'Entry 2019-10-12-hellofresh - blog_data_with_id(" ") did not find exactly one result (as expected): [[]]. Maybe you mistyped an internal link id (or there are multiple blog entries sharing IDs)?'

**Comment by novoid** [comment]
Fixed in the master now. For quick workaround, you could remove the two lines in `config.org` with the length-check. If you set the strings to empty, make sure that their references in the templates are removed as well.
